In [1]:
import numpy as np
import scipy as sc
from time import time
from frequent_direction import FrequentDirections
from scipy.io import mmread

In [2]:
data = mmread('connectus.mtx')

In [3]:
temp = data.toarray()

In [4]:
A = temp.transpose()

In [5]:
del(data)
del(temp)

In [6]:
approxCovarianceMatrixA = np.dot(A.transpose(),A)
approxCovarianceMatrixA

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.13100000e+03,   2.31000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.31000000e+02,   1.31310000e+04, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          3.10000000e+01,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   2.28000000e+02,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   3.80000000e+01]])

In [7]:
Norm_A = np.linalg.norm(A,ord='fro')
Norm_A

1061.8498010547444

In [9]:
# Iterative SVD
Test1 = np.zeros(9)
t1_1 = time()
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op='isvd')
    for i in range(394792):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test1[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)
t1_2 = time()
t1 = t1_2 - t1_1

Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD


In [10]:
t1

38608.07100605965

In [11]:
Test1

array([ 0.04626359,  0.03751108,  0.02501462,  0.01355156,  0.00901289,
        0.00772604,  0.00560132,  0.00525279,  0.00429478])

In [9]:
#Space Saving Direction
Test2 = np.zeros(9)
t2_1 = time()
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op='ssd')
    for i in range(394792):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test2[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)
t2_2 = time()
t2 = t2_2 - t2_1

Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction


In [10]:
t2

20339.706863880157

In [11]:
Test2

array([ 0.03862659,  0.02248347,  0.0151082 ,  0.01072863,  0.00793332,
        0.00595988,  0.0044034 ,  0.00340003,  0.00262113])

In [12]:
# Frequent Direction
Test3 = np.zeros(9)
t3_1 = time()
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op='fd')
    for i in range(394792):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test3[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)
t3_2 = time()
t3 = t3_2 - t3_1

Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction


In [13]:
t3

22322.286201000214

In [14]:
Test3

array([ 0.03617994,  0.0216429 ,  0.01464507,  0.0105097 ,  0.00778555,
        0.00579216,  0.0043586 ,  0.0033246 ,  0.00257939])

In [15]:
# 0.2 Parameterized Frequent Direction
Test4 = np.zeros(9)
t4_1 = time()
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op=0.2)
    for i in range(394792):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test4[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)
t4_2 = time()
t4 = t4_2 - t4_1

Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction


In [16]:
t4

22794.216012954712

In [ ]:
Test4

array([ 0.01643039,  0.01011219,  0.00867995,  0.00589157,  0.00454629,
        0.00393005,  0.00308618,  0.00219552,  0.00197336])

In [ ]:
# 0.8 Parameterized Frequent Direction
Test5 = np.zeros(9)
t5_1 = time()
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op=0.8)
    for i in range(394792):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test5[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)
t5_2 = time()
t5 = t5_2 - t5_1

In [ ]:
t5

In [ ]:
Test5

In [ ]:
Test_1 = [ 0.04626359,  0.03751108,  0.02501462,  0.01355156,  0.00901289,
        0.00772604,  0.00560132,  0.00525279,  0.00429478]

In [ ]:
Test_2 = [ 0.03879371,  0.02275879,  0.01521577,  0.01080329,  0.00798892,
        0.0059705 ,  0.00446608,  0.00339148,  0.00262269]

In [ ]:
Test_3 = [ 0.03617994,  0.02164291,  0.01464507,  0.0105097 ,  0.00778555,
        0.00579216,  0.0043586 ,  0.0033246 ,  0.00257939]

In [ ]:
Test_4 = [ 0.01643039,  0.01011219,  0.00867995,  0.00589157,  0.00454629,
        0.00393005,  0.00308618,  0.00219552,  0.00197336]

In [ ]:
Test_5 = [ 0.0285375 ,  0.01942319,  0.01443317,  0.01053483,  0.00778241,
        0.00578561,  0.00435553,  0.00332577,  0.00257931]

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
x = [20,30,40,50,60,70,80,90,100]
plt.figure(figsize=(15,10))
plt.title('Test Result for connectUS Data', size='xx-large')
plt.ylabel('Covariance Error', size='x-large')
plt.xlabel('Sketch Size', size='x-large')
plt.plot(x,Test1, 'r*-', markersize=10, linewidth=2, label='iSVD')
plt.plot(x,Test2, 'bo-', markersize=10, linewidth=2, label='SSD')
plt.plot(x,Test3, 'gv-', markersize=10, linewidth=2, label='FD')
plt.plot(x,Test4, 'y^-', markersize=10, linewidth=2, label='0.2PFD')
plt.plot(x,Test5, 'c,-', markersize=10, linewidth=2, label='0.8PFD')
plt.tick_params(axis='both', which='major', labelsize=14)
plt.legend(loc=(0.75,0.75), scatterpoints=1)

In [8]:
x = [20,30,40,50,60,70,80,90,100]
plt.figure(figsize=(15,10))
plt.title('Test Result for connectUS Data', size='xx-large')
plt.ylabel('Covariance Error', size='x-large')
plt.xlabel('Sketch Size', size='x-large')
plt.plot(x,Test_1, 'r*-', markersize=10, linewidth=2, label='iSVD')
plt.plot(x,Test_2, 'bo-', markersize=10, linewidth=2, label='SSD')
plt.plot(x,Test_3, 'gv-', markersize=10, linewidth=2, label='FD')
plt.plot(x,Test_4, 'y^-', markersize=10, linewidth=2, label='0.2PFD')
plt.plot(x,Test_5, 'c,-', markersize=10, linewidth=2, label='0.8PFD')
plt.tick_params(axis='both', which='major', labelsize=14)
plt.legend(loc=(0.75,0.75), scatterpoints=1)