In [1]:
import numpy as np
import scipy as sc
from frequent_direction import FrequentDirections
from scipy.io import mmread

In [2]:
data = mmread('/home/duynguyen/Downloads/connectus/connectus.mtx')

In [3]:
temp = data.toarray()

In [4]:
A = temp.transpose()

In [5]:
del(data)
del(temp)

In [6]:
approxCovarianceMatrixA = np.dot(A.transpose(),A)
approxCovarianceMatrixA

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.13100000e+03,   2.31000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.31000000e+02,   1.31310000e+04, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          3.10000000e+01,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   2.28000000e+02,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   3.80000000e+01]])

In [7]:
Norm_A = np.linalg.norm(A,ord='fro')
Norm_A

1061.8498010547444

In [8]:
# Iterative SVD
Test1 = np.zeros(9)
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op='isvd')
    for i in range(394792):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test1[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)

Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD
Matrix Sketching Using iSVD


In [9]:
Test1

array([ 0.04626359,  0.03751108,  0.02501462,  0.01355156,  0.00901289,
        0.00772604,  0.00560132,  0.00525279,  0.00429478])

In [8]:
#Space Saving Direction
Test2 = np.zeros(9)
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op='ssd')
    for i in range(9324):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test2[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)

Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction
Matrix Sketching Using Space Saving Direction


In [9]:
Test2

array([ 0.19618274,  0.19619815,  0.19620054,  0.19619946,  0.19619936,
        0.19619928,  0.19619929,  0.19619928,  0.19619929])

In [11]:
# Frequent Direction
Test3 = np.zeros(9)
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op='fd')
    for i in range(9324):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test3[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)

Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction
Matrix Sketching Using Frequent Direction


In [12]:
Test3

array([ 0.19762928,  0.1970621 ,  0.19677872,  0.19659751,  0.19647778,
        0.19639766,  0.19634116,  0.1963002 ,  0.19627072])

In [13]:
# 0.2 Parameterized Frequent Direction
Test4 = np.zeros(9)
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op=0.2)
    for i in range(9324):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test4[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)

Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction


In [14]:
Test4

array([ 0.19621338,  0.19620113,  0.19620025,  0.19619963,  0.19619954,
        0.19619941,  0.19619936,  0.19619932,  0.19619931])

In [15]:
# 0.8 Parameterized Frequent Direction
Test5 = np.zeros(9)
for j in range(9):    
    l = 20 + 10*j
    fd =  FrequentDirections(l,512,op=0.8)
    for i in range(9324):
        row = A[i,:]
        fd.add(row)
    B = fd.getSketchMatrix()
    approxCovarianceMatrixB = np.dot(B.transpose(),B)
    testMatrix = approxCovarianceMatrixA - approxCovarianceMatrixB
    Test5[j] = np.linalg.norm(testMatrix,ord=2)/(Norm_A**2)
    del(fd)

Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction
Matrix Sketching Using Parameterized Frequent Direction


In [16]:
Test5

array([ 0.19636039,  0.1962448 ,  0.19622801,  0.19621116,  0.19620436,
        0.19620228,  0.19620063,  0.19620022,  0.19619984])

In [1]:
Test_1 = [ 0.04626359,  0.03751108,  0.02501462,  0.01355156,  0.00901289,
        0.00772604,  0.00560132,  0.00525279,  0.00429478]